[package]
name = "rustness"
version = "0.1.0"
authors = ["mynz <rollingteapot@gmail.com>"]
description = "A Famicon/NES emulator"
edition = "2018"

[dependencies]

image = ""
byteorder = ""
quicksilver = ""
clap = ""
