use super::*;

pub(super) const INST_SET: &[InstSpec] = &[
    InstSpec {
        code: 0,
        opcode: Opcode::BRK,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 7,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 1,
        opcode: Opcode::ORA,
        addr_mode: AddrMode::IndirectX(0),
        size: 2,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 2,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 3,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 4,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 5,
        opcode: Opcode::ORA,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 6,
        opcode: Opcode::ASL,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 5,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 7,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 8,
        opcode: Opcode::PHP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 9,
        opcode: Opcode::ORA,
        addr_mode: AddrMode::Immediate(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 10,
        opcode: Opcode::ASL,
        addr_mode: AddrMode::Accumulator,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 11,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 12,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 13,
        opcode: Opcode::ORA,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 14,
        opcode: Opcode::ASL,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 15,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 16,
        opcode: Opcode::BPL,
        addr_mode: AddrMode::Relative(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::OneOrTwo,
    },
    InstSpec {
        code: 17,
        opcode: Opcode::ORA,
        addr_mode: AddrMode::IndirectY(0),
        size: 2,
        cycle: 5,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 18,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 19,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 20,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 21,
        opcode: Opcode::ORA,
        addr_mode: AddrMode::ZeroPageX(0),
        size: 2,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 22,
        opcode: Opcode::ASL,
        addr_mode: AddrMode::ZeroPageX(0),
        size: 2,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 23,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 24,
        opcode: Opcode::CLC,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 25,
        opcode: Opcode::ORA,
        addr_mode: AddrMode::AbsoluteY(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 26,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 27,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 28,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 29,
        opcode: Opcode::ORA,
        addr_mode: AddrMode::AbsoluteX(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 30,
        opcode: Opcode::ASL,
        addr_mode: AddrMode::AbsoluteX(0),
        size: 3,
        cycle: 6,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 31,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 32,
        opcode: Opcode::JSR,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 33,
        opcode: Opcode::AND,
        addr_mode: AddrMode::IndirectX(0),
        size: 2,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 34,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 35,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 36,
        opcode: Opcode::BIT,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 37,
        opcode: Opcode::AND,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 38,
        opcode: Opcode::ROL,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 5,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 39,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 40,
        opcode: Opcode::PLP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 41,
        opcode: Opcode::AND,
        addr_mode: AddrMode::Immediate(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 42,
        opcode: Opcode::ROL,
        addr_mode: AddrMode::Accumulator,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 43,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 44,
        opcode: Opcode::BIT,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 45,
        opcode: Opcode::AND,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 46,
        opcode: Opcode::ROL,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 47,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 48,
        opcode: Opcode::BMI,
        addr_mode: AddrMode::Relative(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::OneOrTwo,
    },
    InstSpec {
        code: 49,
        opcode: Opcode::AND,
        addr_mode: AddrMode::IndirectY(0),
        size: 2,
        cycle: 5,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 50,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 51,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 52,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 53,
        opcode: Opcode::AND,
        addr_mode: AddrMode::ZeroPageX(0),
        size: 2,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 54,
        opcode: Opcode::ROL,
        addr_mode: AddrMode::ZeroPageX(0),
        size: 2,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 55,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 56,
        opcode: Opcode::SEC,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 57,
        opcode: Opcode::AND,
        addr_mode: AddrMode::AbsoluteY(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 58,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 59,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 60,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 61,
        opcode: Opcode::AND,
        addr_mode: AddrMode::AbsoluteX(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 62,
        opcode: Opcode::ROL,
        addr_mode: AddrMode::AbsoluteX(0),
        size: 3,
        cycle: 6,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 63,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 64,
        opcode: Opcode::RTI,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 65,
        opcode: Opcode::EOR,
        addr_mode: AddrMode::IndirectX(0),
        size: 2,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 66,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 67,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 68,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 69,
        opcode: Opcode::EOR,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 70,
        opcode: Opcode::LSR,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 5,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 71,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 72,
        opcode: Opcode::PHA,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 73,
        opcode: Opcode::EOR,
        addr_mode: AddrMode::Immediate(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 74,
        opcode: Opcode::LSR,
        addr_mode: AddrMode::Accumulator,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 75,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 76,
        opcode: Opcode::JMP,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 77,
        opcode: Opcode::EOR,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 78,
        opcode: Opcode::LSR,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 79,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 80,
        opcode: Opcode::BVC,
        addr_mode: AddrMode::Relative(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::OneOrTwo,
    },
    InstSpec {
        code: 81,
        opcode: Opcode::EOR,
        addr_mode: AddrMode::IndirectY(0),
        size: 2,
        cycle: 5,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 82,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 83,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 84,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 85,
        opcode: Opcode::EOR,
        addr_mode: AddrMode::ZeroPageX(0),
        size: 2,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 86,
        opcode: Opcode::LSR,
        addr_mode: AddrMode::ZeroPageX(0),
        size: 2,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 87,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 88,
        opcode: Opcode::CLI,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 89,
        opcode: Opcode::EOR,
        addr_mode: AddrMode::AbsoluteY(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 90,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 91,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 92,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 93,
        opcode: Opcode::EOR,
        addr_mode: AddrMode::AbsoluteX(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 94,
        opcode: Opcode::LSR,
        addr_mode: AddrMode::AbsoluteX(0),
        size: 3,
        cycle: 6,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 95,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 96,
        opcode: Opcode::RTS,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 97,
        opcode: Opcode::ADC,
        addr_mode: AddrMode::IndirectX(0),
        size: 2,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 98,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 99,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 100,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 101,
        opcode: Opcode::ADC,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 102,
        opcode: Opcode::ROR,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 5,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 103,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 104,
        opcode: Opcode::PLA,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 105,
        opcode: Opcode::ADC,
        addr_mode: AddrMode::Immediate(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 106,
        opcode: Opcode::ROR,
        addr_mode: AddrMode::Accumulator,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 107,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 108,
        opcode: Opcode::JMP,
        addr_mode: AddrMode::Indirect(0),
        size: 3,
        cycle: 5,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 109,
        opcode: Opcode::ADC,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 110,
        opcode: Opcode::ROR,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 111,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 112,
        opcode: Opcode::BVS,
        addr_mode: AddrMode::Relative(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::OneOrTwo,
    },
    InstSpec {
        code: 113,
        opcode: Opcode::ADC,
        addr_mode: AddrMode::IndirectY(0),
        size: 2,
        cycle: 5,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 114,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 115,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 116,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 117,
        opcode: Opcode::ADC,
        addr_mode: AddrMode::ZeroPageX(0),
        size: 2,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 118,
        opcode: Opcode::ROR,
        addr_mode: AddrMode::ZeroPageX(0),
        size: 2,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 119,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 120,
        opcode: Opcode::SEI,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 121,
        opcode: Opcode::ADC,
        addr_mode: AddrMode::AbsoluteY(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 122,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 123,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 124,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 125,
        opcode: Opcode::ADC,
        addr_mode: AddrMode::AbsoluteX(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 126,
        opcode: Opcode::ROR,
        addr_mode: AddrMode::AbsoluteX(0),
        size: 3,
        cycle: 6,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 127,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 128,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 129,
        opcode: Opcode::STA,
        addr_mode: AddrMode::IndirectX(0),
        size: 2,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 130,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 131,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 132,
        opcode: Opcode::STY,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 133,
        opcode: Opcode::STA,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 134,
        opcode: Opcode::STX,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 135,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 136,
        opcode: Opcode::DEY,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 137,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 138,
        opcode: Opcode::TXA,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 139,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 140,
        opcode: Opcode::STY,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 141,
        opcode: Opcode::STA,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 142,
        opcode: Opcode::STX,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 143,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 144,
        opcode: Opcode::BCC,
        addr_mode: AddrMode::Relative(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::OneOrTwo,
    },
    InstSpec {
        code: 145,
        opcode: Opcode::STA,
        addr_mode: AddrMode::IndirectY(0),
        size: 2,
        cycle: 5,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 146,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 147,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 148,
        opcode: Opcode::STY,
        addr_mode: AddrMode::ZeroPageX(0),
        size: 2,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 149,
        opcode: Opcode::STA,
        addr_mode: AddrMode::ZeroPageX(0),
        size: 2,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 150,
        opcode: Opcode::STX,
        addr_mode: AddrMode::ZeroPageY(0),
        size: 2,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 151,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 152,
        opcode: Opcode::TYA,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 153,
        opcode: Opcode::STA,
        addr_mode: AddrMode::AbsoluteY(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 154,
        opcode: Opcode::TXS,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 155,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 156,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 157,
        opcode: Opcode::STA,
        addr_mode: AddrMode::AbsoluteX(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 158,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 159,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 160,
        opcode: Opcode::LDY,
        addr_mode: AddrMode::Immediate(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 161,
        opcode: Opcode::LDA,
        addr_mode: AddrMode::IndirectX(0),
        size: 2,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 162,
        opcode: Opcode::LDX,
        addr_mode: AddrMode::Immediate(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 163,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 164,
        opcode: Opcode::LDY,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 165,
        opcode: Opcode::LDA,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 166,
        opcode: Opcode::LDX,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 167,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 168,
        opcode: Opcode::TAY,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 169,
        opcode: Opcode::LDA,
        addr_mode: AddrMode::Immediate(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 170,
        opcode: Opcode::TAX,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 171,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 172,
        opcode: Opcode::LDY,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 173,
        opcode: Opcode::LDA,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 174,
        opcode: Opcode::LDX,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 175,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 176,
        opcode: Opcode::BCS,
        addr_mode: AddrMode::Relative(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::OneOrTwo,
    },
    InstSpec {
        code: 177,
        opcode: Opcode::LDA,
        addr_mode: AddrMode::IndirectY(0),
        size: 2,
        cycle: 5,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 178,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 179,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 180,
        opcode: Opcode::LDY,
        addr_mode: AddrMode::ZeroPageX(0),
        size: 2,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 181,
        opcode: Opcode::LDA,
        addr_mode: AddrMode::ZeroPageX(0),
        size: 2,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 182,
        opcode: Opcode::LDX,
        addr_mode: AddrMode::ZeroPageY(0),
        size: 2,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 183,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 184,
        opcode: Opcode::CLV,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 185,
        opcode: Opcode::LDA,
        addr_mode: AddrMode::AbsoluteY(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 186,
        opcode: Opcode::TSX,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 187,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 188,
        opcode: Opcode::LDY,
        addr_mode: AddrMode::AbsoluteX(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 189,
        opcode: Opcode::LDA,
        addr_mode: AddrMode::AbsoluteX(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 190,
        opcode: Opcode::LDX,
        addr_mode: AddrMode::AbsoluteY(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 191,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 192,
        opcode: Opcode::CPY,
        addr_mode: AddrMode::Immediate(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 193,
        opcode: Opcode::CMP,
        addr_mode: AddrMode::IndirectX(0),
        size: 2,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 194,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 195,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 196,
        opcode: Opcode::CPY,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 197,
        opcode: Opcode::CMP,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 198,
        opcode: Opcode::DEC,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 5,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 199,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 200,
        opcode: Opcode::INY,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 201,
        opcode: Opcode::CMP,
        addr_mode: AddrMode::Immediate(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 202,
        opcode: Opcode::DEX,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 203,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 204,
        opcode: Opcode::CPY,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 205,
        opcode: Opcode::CMP,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 206,
        opcode: Opcode::DEC,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 207,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 208,
        opcode: Opcode::BNE,
        addr_mode: AddrMode::Relative(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::OneOrTwo,
    },
    InstSpec {
        code: 209,
        opcode: Opcode::CMP,
        addr_mode: AddrMode::IndirectY(0),
        size: 2,
        cycle: 5,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 210,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 211,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 212,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 213,
        opcode: Opcode::CMP,
        addr_mode: AddrMode::ZeroPageX(0),
        size: 2,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 214,
        opcode: Opcode::DEC,
        addr_mode: AddrMode::ZeroPageX(0),
        size: 2,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 215,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 216,
        opcode: Opcode::CLD,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 217,
        opcode: Opcode::CMP,
        addr_mode: AddrMode::AbsoluteY(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 218,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 219,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 220,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 221,
        opcode: Opcode::CMP,
        addr_mode: AddrMode::AbsoluteX(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 222,
        opcode: Opcode::DEC,
        addr_mode: AddrMode::AbsoluteX(0),
        size: 3,
        cycle: 6,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 223,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 224,
        opcode: Opcode::CPX,
        addr_mode: AddrMode::Immediate(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 225,
        opcode: Opcode::SBC,
        addr_mode: AddrMode::IndirectX(0),
        size: 2,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 226,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 227,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 228,
        opcode: Opcode::CPX,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 229,
        opcode: Opcode::SBC,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 3,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 230,
        opcode: Opcode::INC,
        addr_mode: AddrMode::ZeroPage(0),
        size: 2,
        cycle: 5,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 231,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 232,
        opcode: Opcode::INX,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 233,
        opcode: Opcode::SBC,
        addr_mode: AddrMode::Immediate(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 234,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 235,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 236,
        opcode: Opcode::CPX,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 237,
        opcode: Opcode::SBC,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 238,
        opcode: Opcode::INC,
        addr_mode: AddrMode::Absolute(0),
        size: 3,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 239,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 240,
        opcode: Opcode::BEQ,
        addr_mode: AddrMode::Relative(0),
        size: 2,
        cycle: 2,
        ext_cycle: ExtCycle::OneOrTwo,
    },
    InstSpec {
        code: 241,
        opcode: Opcode::SBC,
        addr_mode: AddrMode::IndirectY(0),
        size: 2,
        cycle: 5,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 242,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 243,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 244,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 245,
        opcode: Opcode::SBC,
        addr_mode: AddrMode::ZeroPageX(0),
        size: 2,
        cycle: 4,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 246,
        opcode: Opcode::INC,
        addr_mode: AddrMode::ZeroPageX(0),
        size: 2,
        cycle: 6,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 247,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 248,
        opcode: Opcode::SED,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 249,
        opcode: Opcode::SBC,
        addr_mode: AddrMode::AbsoluteY(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 250,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 251,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 252,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
    InstSpec {
        code: 253,
        opcode: Opcode::SBC,
        addr_mode: AddrMode::AbsoluteX(0),
        size: 3,
        cycle: 4,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 254,
        opcode: Opcode::INC,
        addr_mode: AddrMode::AbsoluteX(0),
        size: 3,
        cycle: 6,
        ext_cycle: ExtCycle::One,
    },
    InstSpec {
        code: 255,
        opcode: Opcode::NOP,
        addr_mode: AddrMode::Implied,
        size: 1,
        cycle: 2,
        ext_cycle: ExtCycle::Zero,
    },
];
